### ISSUE TITLE
Your new template is pending approval

### ISSUE THREAD

**Issue by ShivangiM** [awaazde/awaazde-api-client-sdk#1]
When running python demo.py

Why do I get mail saying:
"Thank you for creating a new Awaaz.De template. Please allow up to 12 hours for it to be reviewed and activated by AD Staff."?

And even after 12 hours I haven't received any notification.

**Comment by nikhiln** [comment]
@ShivangiM There should be someone from my team reached out to you. If not please reopen the issue and comment here.
